stages:
  - build
  - run

gcc-8:
  stage: build
  retry: 1
  tags:
    - docker
    - gpu
  script:
    - make
  artifacts:
    untracked: true
    paths:
      - build/
    expire_in: 1 month

resnet50:
  stage: run
  retry: 1
  tags:
    - docker
    - gpu
  script:
    - . /etc/roaster/scripts/pkgs/env/mirror.sh
    - mkdir -p test/resnet50
    - pushd test/resnet50
    - curl -sSL "$GIT_MIRROR/caffe2/models/raw/master/$(basename "$(pwd)")/init_net.pb?inline=false" > init_net.pb
    - curl -sSL "$GIT_MIRROR/caffe2/models/raw/master/$(basename "$(pwd)")/predict_net.pbtxt?inline=false" > predict_net.pbtxt
    - curl -sSL "$GIT_MIRROR/caffe2/models/raw/master/$(basename "$(pwd)")/value_info.json?inline=false" > value_info.json
    - popd
    - make run

