stages:
  - build
  - run

gcc-7:
  stage: build
  retry: 1
  tags:
    - docker
    - gpu
  script:
    - mkdir -p build
    - cd build
    - . /opt/intel/compilers_and_libraries/$(uname -s | tr '[A-Z]' '[a-z]')/bin/compilervars.sh intel64
    - set +e && . scl_source enable devtoolset-7 && set -e
    - cmake
          -DCMAKE_C_COMPILER=gcc
          -DCMAKE_C_FLAGS="-g"
          -DCMAKE_CXX_COMPILER=g++
          -DCMAKE_CXX_FLAGS="-g"
          -DCMAKE_MODULE_PATH="/usr/local/src/pytorch/cmake/Modules"
          -DCMAKE_VERBOSE_MAKEFILE=ON
          -DPYBIND11_PYTHON_VERSION=2.7
          -GNinja
          ..
    - cmake --build .
  artifacts:
    untracked: true
    paths:
      - build/
    expire_in: 1 month

alexnet:
  stage: run
  retry: 1
  tags:
    - docker
    - gpu
  script:
    - cd build
    - export PYTHONPATH="$(ls -d /usr/local/lib/python2.7/site-packages | paste -sd':' -):$PYTHONPATH"
    - mkdir -p alexnet
    - pushd alexnet
    - . /etc/codingcafe/scripts/pkgs/env-mirror.sh
    - curl -sSL "$GIT_MIRROR/caffe2/models/raw/master/$(basename "$(pwd)")/init_net.pb?inline=false" > init_net.pb
    - curl -sSL "$GIT_MIRROR/Mirrors/caffe2/models/raw/master/$(basename "$(pwd)")/predict_net.pb?inline=false" > predict_net.pbtxt
    - curl -sSL "$GIT_MIRROR/Mirrors/caffe2/models/raw/master/$(basename "$(pwd)")/value_info.json?inline=false" > value_info.json
    - popd
    - bin/siphon --caffe2_log_level 0 --load alexnet --save c2net --save_onnx model.onnx
