stages:
  - build

gcc-7:
  stage: build
  retry: 1
  tags:
    - docker
    - gpu
  script:
    - mkdir -p build
    - cd build
    - . /opt/intel/compilers_and_libraries/$(uname -s | tr '[A-Z]' '[a-z]')/bin/compilervars.sh intel64
    - set +e && . scl_source enable devtoolset-7 && set -e
    - cmake
          -DCMAKE_C_COMPILER=gcc
          -DCMAKE_C_FLAGS="-g"
          -DCMAKE_CXX_COMPILER=g++
          -DCMAKE_CXX_FLAGS="-g"
          -DCMAKE_MODULE_PATH="/usr/local/src/pytorch/cmake/Modules"
          -DCMAKE_VERBOSE_MAKEFILE=ON
          -DPYBIND11_PYTHON_VERSION=2.7
          -GNinja
          ..
    - cmake --build .
    - export PYTHONPATH="$(ls -d /usr/local/lib/python*/site-packages | paste -sd':' -):$PYTHONPATH"

